---
git:
  submodules: false
bundler_args: --without development debug
before_install:
  - cp spec/config/*.yml config
  - bundle config without development:production
before_script:
  - bundle exec rake jetty:unzip jetty:config jetty:start delayed_job:start
  - bundle exec rake db:migrate
notifications:
  irc: "chat.freenode.net#projectvov"
language: ruby
rvm:
  - 2.1.7
sudo: false
