---
git:
  submodules: false
bundler_args: --with postgres aws --without development debug
env:
  - FCREPO_URL=http://127.0.0.1:8986/rest SOLR_URL=http://127.0.0.1:8985/solr/hydra-test RAILS_ENV=test DATABASE_URL=postgresql://postgres:@127.0.0.1:5432/
services:
  - mysql2
  - redis-server
before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo rm -vf /etc/apt/sources.list.d/*hhvm*
  - sudo apt-get update
  - sudo apt-get install mediainfo
  - sudo ln -s /usr/bin/lsof /usr/sbin/lsof
  - cp config/controlled_vocabulary.yml.example config/controlled_vocabulary.yml
  - bundle config without development:production
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rake
language: ruby
jdk:
  - oraclejdk8
rvm:
  - 2.4
  - 2.5
dist: trusty
sudo: required
