version: '3'

volumes:
  streaming:
    driver: local
  database:
    driver: local
  fcrepo:
    driver: local
  work:
    driver: local
  solr:
    driver: local
  redis:
    driver: local

services:
  db:
    image: postgres:9.6-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: avalon
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fcrepo:
    image: ualbertalib/docker-fcrepo4
    volumes:
      - fcrepo:/fcrepo4-data
    ports:
      - "8984:8080"

  solr:
    image: solr:6.6
    ports:
      - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/config:/config
      - ./solr/scripts/solr-precreate-avalon.sh:/docker-entrypoint-initdb.d/solr-precreate-avalon.sh

  matterhorn:
    image: avalonmediasystem/matterhorn
    volumes:
      - ./masterfiles:/masterfiles
      - streaming:/streamfiles
      - work:/work
    ports:
      - "8080:8080"
  hls:
    image: avalonmediasystem/nginx
    volumes:
      - streaming:/data
    ports:
       - "8880:80"

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  avalon:
    image: avalonmediasystem/avalon:6.x-dev
    command: "bin/docker-start"
    depends_on:
      - db
      - fcrepo
      - solr
      - redis
    environment:
      - APP_NAME=avalon
      - ASSET_HOST=http://localhost:3000
      - AVALON_BRANCH=develop
      - AVALON_DB_PASSWORD=avalondb
      - SETTINGS__DOMAIN=http://localhost:3000
      - CONTROLLED_VOCABULARY=config/controlled_vocabulary.yml
      - DATABASE_URL=postgresql://avalon:mysecretpassword@db:5432/
      - SETTINGS__DROPBOX__PATH=/masterfiles
      - SETTINGS__DROPBOX__UPLOAD_URI=./masterfiles
      - EMAIL_COMMENTS
      - EMAIL_NOTIFICATION
      - EMAIL_SUPPORT
      - FCREPO_URL=http://fcrepo:8080/fcrepo/rest
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY=delete
      - MATTERHORN_URL=http://matterhorn_system_account:CHANGE_ME@matterhorn:8080/
      - MATTERHORN_CLIENT_MEDIA_PATH=/masterfiles
      - MATTERHORN_SERVER_MEDIA_PATH=/masterfiles
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=development
      - REDIS_URL=redis://redis/90210
      - SECRET_KEY_BASE=abcd
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=http://solr:8983/solr/development
      - SOLR_TEST_URL=http://solr:8983/solr/test
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__STREAMING__STREAM_DEFAULT_QUALITY=medium
      - SETTINGS__STREAMING__HTTP_BASE=http://localhost:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
    volumes:
      - ./masterfiles:/masterfiles
      - ./gems:/gems
      - .:/home/app/avalon
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
