default: &default
  adapter: solr
  url: <%= Rails.application.secrets.solr_url %>
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/development' %>
test:
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] || 'http://localhost:8983/solr/test' %>
uat:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
