default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: rails
  username: rails
  password: rails
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: rails_dev

# This config is for Travis
test:
  adapter: mysql2
  database: rails_test
  username: root
  encoding: utf8

staging:
  <<: *default
  database: rails_staging

production:
  <<: *default
