default: &default
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_URL'] || 'http://localhost:8984/fcrepo/rest' %>
  base_path: /dev
development:
  <<: *default
test:
  <<: *default
uat:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
