development: &PROTOTYPE
  dropbox:
    path       : '/srv/avalon/dropbox'
    upload_url : 'sftp://localhost/srv/avalon/dropbox'
    username   : 'avalon'
    password   : 'avalon'
test: *PROTOTYPE
production: *PROTOTYPE
