---
<% Array(Rails.application.secrets.lti_servers).each do |server| %>
<%= server %>:
  :uid: :lis_person_contact_email_primary
  :email: :lis_person_contact_email_primary
  :context_id: :context_label
  :context_name: :context_label
<% end %>