---
<%# Rails.application.secrets.lti_servers holds a list of server names
    For each server, we need to map LTI request variables to something Avalon/OmniAuth can use.
    Here, `context_id` is the course name, which corresponds to an access group in Avalon. %>
<% Array(Rails.application.secrets.lti_servers).each do |server| %>
<%= server %>:
  :uid: :lis_person_contact_email_primary
  :email: :lis_person_contact_email_primary
  :context_id: :context_label
  :context_name: :context_label
<% end %>
