development: &default
  url: <%= ENV['MATTERHORN_URL'] ||
           "http://matterhorn_system_account:CHANGE_ME@localhost:8080/" %> 
test:
  <<: *default
uat:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
