archivist:
  - archivist1@example.com
  - rogersna
  - cjcolvar
donor:
  - donor1@example.com
researcher:
  - cjcolvar
  - researcher1@example.com
patron:
  - pdinh
  - patron1@example.com
admin_policy_object_editor:
  - archivist1@example.com
  - rogersna
  - cjcolvar
