uva-only:
  - uva-only
archivist:
  - archivist1@example.com
  - archivist2
  - pdinh
  - mnotess
  - rogersna
  - cjcolvar
donor:
  - donor1@example.com
researcher:
  - researcher1@example.com
registered:
  - pdinh
  - rogersna
  - cjcolvar
admin_policy_object_editor:
  - archivist1@example.com
  - pdinh
  - cjcolvar
  - rogersna
  - mnotess
patron:
  - patron1
