uva-only:
  - uva-only
archivist:
  - archivist1@example.com
  - archivist2
  - pdinh
  - mnotess
  - rogersna
  - cjcolvar
  - 80000493756
  - 80000493749
  - 80000496023
  - 80000496644
  - jlhardes
  - 80000497619
  - 80000478586
  - chris.colvard@gmail.com
donor:
  - donor1@example.com
researcher:
  - researcher1@example.com
registered:
  - pdinh
  - rogersna
  - cjcolvar
admin_policy_object_editor:
  - archivist1@example.com
  - pdinh
  - cjcolvar
  - rogersna
  - mnotess
  - 80000493756
  - 80000493749
  - 80000496023
  - 80000496644
  - jlhardes
  - 80000497619
  - 80000478586
  - chris.colvard@gmail.com
patron:
  - patron1
