uva-only:
  - uva-only
donor:
  - donor1@example.com
researcher:
  - researcher1@example.com
registered:
  - pdinh
admin_policy_object_editor:
  - archivist1@example.com
  - pdinh
  - cjcolvar
  - rogersna
  - mnotess
patron:
  - 
archivist:
  - archivist1@example.com
  - pdinh
  - mnotess
  - rogersna
